### PR TITLE
Add property tests for the standard library's Enum.slide/3

### PR DESCRIPTION
**Pull request by s3cur3**
These are the property tests I wrote while developing `Enum.slide/3`. Following @whatyouhide's [invitation](https://mobile.twitter.com/whatyouhide/status/1484547725429555200), I thought it'd be nice to have these run daily against the latest version of the standard library. 😄

I don't think the stdlib tests run against every PR to `stream_data`, but [they've passed on my fork](https://github.com/s3cur3/stream_data/runs/4971869806?check_suite_focus=true).

### CODE REVIEW

**Comment by s3cur3** [comment]
Oh, uh… hehe. This will of course fail prior to 1.13. 🤔

**Comment by whatyouhide** [comment]
@s3cur3 you can add conditional testing for that, something along these lines:

```elixir
# TODO: Remove when we depend on Elixir 1.13+.
if function_exported?(Enum, :slide, 3) do
  # What you have now
  property ...
end
```

**Comment by s3cur3** [comment]
Aha, thanks for the tip! 😄 Fix pushed. 👍

**Comment by whatyouhide** [comment]
Awesome, thanks @s3cur3! 💟

**Pull request merged**
